apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert -f compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert -f compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DBHOST
              value: database
          image: hellboyhha/dotnet-mysql-sample-app-api:latest
          name: api
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always