apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 7
  targetCPUUtilizationPercentage: 50  # Target average CPU utilization percentage
