apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert -f compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert -f compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: Usersdb
            - name: MYSQL_PASSWORD
              value: pass@word1234
            - name: MYSQL_ROOT_PASSWORD
              value: Root0++
            - name: MYSQL_USER
              value: newuser
          image: mysql:8.0.22
          name: database
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: datafiles
            - mountPath: /docker-entrypoint-initdb.d/1.sql
              name: database-claim1
      restartPolicy: Always
      volumes:
        - name: datafiles
          persistentVolumeClaim:
            claimName: datafiles
        - name: database-claim1
          persistentVolumeClaim:
            claimName: database-claim1